# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김낙영
title: Java & Spring 백엔드 개발자
email: ks25ny@gmail.com
website: https://datajoy.tistory.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: DataJoyKim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 8년차 백엔드 개발자로<br>
  넷마블에서 HR시스템의 백엔드 플랫폼 개발을 하고있습니다.<br>
  <br>
  복잡한 도메인 환경에서 지속 가능한 소프트웨어를 개발하기 위해 고민하는 개발자입니다.<br>
  <br>
  주도적으로 개선점을 찾아 해결하며 성장하는 것을 좋아합니다.<br>
  데이터를 의미있게 사용 할 수 있는 파이프라인 구축하는 것을 좋아합니다.<br>
  <br>
  동료와 같이 성장하기 위해 기술 공유하며 피드백하는것을 즐기며<br>
  개발자가 어떻게하면 효율적으로 개발할지 생산성을 높이는것에도 관심있습니다.
  
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 넷마블 HR시스템팀
        sub_title: Java & Spring 백엔드 개발자
        caption: 2017.04 ~ 현재
        link: 
        quote: >
          직원수 7,400명, 계열사 14개에 HR 플랫폼 제공하는 시스템 개발
        description: |
            - 외부 eHR 솔루션을 사용하는 규모가 작은 환경에서 초기 멤버로 시작하여,<br>빠르게 변화하는 HR의 복잡한 요구사항을 유연하게 대응하기 위해 자체 시스템을 개발
            - business service(근태시스템,업적평가시스템,역량진단시스템,채용시스템,칭찬시스템)의 도메인 모델링 및 아키텍처 설계, application 개발/운영
            - 분산 된 business service를 적은 리소스로 효율적인 개발/운영을 하기 위해,<br>platform service(인증, 접근제어, 알람, 배치, 파일관리, 로깅, 모니터링, 검색엔진, config)를 개발 및 구축
            - 공통 기능을 모듈화하여 eHR Framework를 구축함으로써, 개발자가 비즈니스 로직 개발에 집중할 수 있는 환경 구축
            - 관리자 페이지와 같은 정형화된 요구사항에 생산성을 효율화 하기 위해 Admin Builder를 개발하여<br>WEB 콘솔에서 설정 기반으로 API와 UI를 생성하여 관리자 페이지를 제공하는 환경 구축
            - 플랫폼의 기반을 만들고 개발 환경을 개선한 성과를 인정받아 <mark>2022년 넷마블 챌린지 어워드</mark>를 수상
      
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 업무자동화서비스 구축
        sub_title: 넷마블
        caption: 2025.01 ~ 현재
        description: | # this will include new lines to allow paragraphs
            - Admin Builder에 Spring Quartz를 활용한 스케줄링 기능 및 LLM API를 연동 기능을 추가
            
      - layout: left
        title: NHR 플랫폼 안정화 작업
        sub_title: 넷마블
        caption: 2024.03 ~ 2024.12
        description: | # this will include new lines to allow paragraphs
            - 플랫폼이 성장하면서 복잡도 상승으로 인해 운영 및 관리 리소스 증가와 장애 발생 시 대응이 늦어 개선작업 진행
            - 서비스 구간 장애 탐지하기 위한 Health Check application 개발
            - 모든 서비스에 circuit breaker를 적용하여 장애 전파를 최소화
            - trace id를 발급하고 전파하여 모든 서비스에서 로깅을 통해 장애를 추적하기 쉽도록 개선
            - 분산된 서버를 내부와 외부로만 구분하여 통합 작업하여 관리 리소스 최소화
            - 인증서비스, 알람서비스, 접근제어서비스, config 서비스를 Admin Builder로 통합하여 관리 리소스 최소화
            - 자체 구축한 Jenkins의 CI/CD 환경에서 넷마블 플랫폼에서 지원하는 Gitlab으로 CI/CD 환경을 구축하여 관리 리소스 최소화

      - layout: left
        title: Admin Builder 개발
        sub_title: 넷마블
        caption: 2023.06 ~ 2024.01
        description: | # this will include new lines to allow paragraphs
            - 정형화 되고 단순 반복적인 관리자 페이지 개발의 생산성을 높이기 위해<br>WEB 콘솔에서 설정으로 API와 view를 생성하는 application 개발
            - SQL, 엔티티, Rest Client, 파일관리, 알람전송 기능들을 조합하고 인증과 권한을 설정하여 API 생성,<br>원하는 view 템플릿을 선택하고 설정하면 화면 구성 가능
            - 아키텍쳐 설계 및 application 개발 수행
            - 권한 구조를 tree 구조로 설계하여 조직별 권한, 직책별 권한, 역할별 권한 등 다양하고 복잡한 관리자 권한을 유연하게 대응가능하게 개발
            - 단순 CRUD 화면을 개발하는데 5분 이내 작업 가능. 복잡한 구조도 커스텀 개발 가능하도록 설계
            - 사용기술: Tomcat, Java, Spring, Mysql, JSP
            
      - layout: left
        title: NHR 플랫폼 구축
        sub_title: 넷마블
        caption: 2023.01 ~ 2024.03
        description: | # this will include new lines to allow paragraphs
            - NHR 플랫폼 구축을 통해 개발자가 비즈니스 로직 개발에만 집중하고 적은 리소스로 시스템을 운영 할 수 있는 환경 구축
            - 유연한 시스템 구조를 위해 물리적 구조와 개념적 구조를 분리하여 아키텍쳐 설계
              - business service의 공통 개발을 지원하는 common service(인증, 접근제어, 알람, 파일관리, 검색엔진, config) 구성
              - 플랫폼을 운영하는 operation service(로깅, 모니터링, 배치, 성능테스트, CI/CD) 구성
              - 플랫폼을 관리하는 admin service(Admin Builder)로 구성
            - 인증서비스, 알람서비스, 접근제어서비스, config 서비스를 개발하여 API로 business service에 제공함으로써<br>비즈니스 외 서비스에 대해 의존성을 낮추고 중앙에서 관리될 수 있도록 개발
            - application의 비즈니스 로직 외 플랫폼 요소는 컴포넌트화 하여 e-HR Framework로 구축
            - SSO를 통한 인증 로직 표준화
            - 팀 내 개발 프로세스 표준화
            - Jenkins를 활용한 CI/CD 환경 구축
            - 개발자의 인프라 운영 및 관리에 대한 인지적 부하 감소
              - 넷마블 플랫폼에서 지원하는 Terraform을 활용하여 서버 및 application의 설치/설정/실행을 프로비저닝
              - 자체 Oracle Virtual Box으로 구성한 분산된 개발 환경에서 넷마블 클라우드 서버로 신규 dev/qa/stage 환경 구축
              - 인프라 효율적 관리를 위한 WEB 페이지 개발
                        
      - layout: left
        title: 파일관리서비스 개발
        sub_title: 넷마블
        caption: 2022.12 ~ 2023.06
        description: | # this will include new lines to allow paragraphs
            - 아키텍쳐 설계 및 개발
            - 사용기술: Java, Spring, Mysql
         
      - layout: left
        title: 중앙 로깅 시스템 구축
        sub_title: 넷마블
        caption: 2021.04 ~ 2021.12
        description: | # this will include new lines to allow paragraphs
            - 분산 된 application에서 발생한 로그를 중앙에서 수집 관리하여 문제 분석 시간을 단축 시키고<br>로그를 통해 사용자 패턴을 분석하여 더 나은 서비스를 제공하는 환경 구축
            - 아키텍쳐 설계 및 개발 수행
            - Back-End 로그는 일반적으로 Filebeat를 통해 수집하고 application 자체에서 전송해야하는 경우 컴포넌트를 제공하여 RabbitMQ로 로그를 전송하여 수집
            - Front-End 로그는 Spring Boot로 API 서버 구축하여 API를 통해 수집
            - Logstash로 수집하여 Mysql에 적재하고 로그 검색 할 수있는 WEB 페이지 제공
            - 사용기술: Java, Spring Boot, RabbitMQ, Logstash, Filebeat, Mysql
            
      - layout: left
        title: 신규 채용시스템 개발/운영
        sub_title: 넷마블
        caption: 2022.12 ~ 2023.06
        link: https://career.netmarble.com
        description: | # this will include new lines to allow paragraphs
            - 백엔드 플랫폼 개발과 비즈니스 개발자의 원할한 개발을 위한 지원을 수행
            - 인증 및 간편로그인 기능 여러 OAuth 서비스를 통합 
            - 외부용 시스템 아키텍처 설계
            - 사용기술: Nginx, Tomcat, Java, Spring, Mysql
          
      - layout: left
        title: 신규 칭찬시스템 개발/운영
        sub_title: 넷마블
        caption: 2021.09 ~ 2021.12
        description: | # this will include new lines to allow paragraphs
            - 요구사항을 분석하여 도메인 모델링 및 설계, 백엔드 개발 진행
            - 지속적으로 증가하는 칭찬 글의 검색성능 향상을 위한 검색 파이프라인 설계와 ElasticSearch로 검색엔진 구축.
            - 랭킹과 사용자가 많이 접근하는 홈화면의 칭찬 글 내역의 성능향상을 위해 Ehcache로 캐싱.
            - 사용기술: Tomcat, Java, Spring, Ehcache, Oracle, ElasticSearch, Logstash, Kibana
            
      - layout: left
        title: 신규 평가시스템 개발/운영
        sub_title: 넷마블
        caption: 2019.12 ~ 2024.06
        description: | # this will include new lines to allow paragraphs
            - 도메인 모델링 및 아키텍처 설계하여 백엔드 application 개발 진행
            - 비즈니스 로직의 복잡성을 낮추기 위해 도메인 주도 설계를 기반으로 아키텍처 설계
              - 역량진단,목표수립,상시피드백,개인업적평가,조직평가,종합피드백,수시평가,리더적합도평가로 모듈을 나누어 인지적 부하를 낮추고 의존성을 관리
              - 공통 로직은 AOP를 통해 처리하는 구조로 설계
              - 비즈니스 로직은 도메인 객체에 구현하고 Service Layer에서 오케스트레이션하여 도메인 객체를 보호하는 구조로 개발
            - 비즈니스 로직과 요구사항으로 추출한 시스템 정책 문서를 일치시켜 이해관계자와의 커뮤니케이션 비용을 줄임
            - 도메인 중심 설계의 개발 전체 과정을 팀 내 개발 프로세스로 표준화하여 시스템의 복잡성을 낮추면서 생산성을 높임
            - pinpoint와 nGrinder를 도입하여 성능테스트 환경 개선
            - 사용기술: Tomcat, Java, Spring, Oracle
            
      - layout: left
        title: 신규 근태시스템 개발/운영
        sub_title: 넷마블
        caption: 2017.12 ~ 2020.03
        description: | # this will include new lines to allow paragraphs
            - 선택적근로 정책 도입에 따른 API 개발 진행
            - 정책 변경/추가에 따른 비즈니스 로직 개선 작업 진행
            - Artillery로 성능테스트를 통한 Tomcat Thread Pool와 DBCP 최적화
            - 배포 자동화 script 개발
            - 사용기술: Tomcat, Java, Spring, Oracle
            
      - layout: left
        title: e-HR 운영 및 유지보수
        sub_title: 넷마블
        caption: 2017.06 ~ 2018.12
        description: | # this will include new lines to allow paragraphs
            - 외부 e-HR 솔루션 Framework으로 요구사항에 따른 개발 진행
            - 연장근무 신청/결재/관리 개발
            - 퇴근교통비 신청/결재/관리 개발
            - 의료비 신청/결재/관리 개발
            - 전자결재 모듈 개발
          
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Back-End
        description: >
          - Java
          
          - Spring MVC, Spring Boot, Spring Security, Spring AOP, JWT, Spring Quartz, JPA, MyBatis
          
          - Oracle, MySQL, Mssql
          
          - Tomcat, Nginx
          
          - RabbitMQ, Ehcache, Elasticsearch, Kibana, Logstash, Filebeat
          
          - pinpoint, nGrinder, Jenkins, gitlab, JIRA, Confluence, IntelliJ, eclipse

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
